version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - echo "Running HTML lint..."
      - npx htmlhint index.html
      - echo "Build completed successfully"
artifacts:
  files:
    - **/*
    - app.zip
    - build_hash.txt
    
