version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - echo "Running HTML lint..."
      - npx htmlhint index.html
      - echo "Packaging artefact..."
      - zip -r app.zip index.html css/ js/
      - echo "Generating checksum..."
      - sha256sum app.zip > build_hash.txt
      - echo "Build completed successfully"
      - sha256sum app.zip > build_hash.txt
      - cat build_hash.txt   # prints hash in logs for verification
artifacts:
  files:
    - app.zip
    - build_hash.txt
    
